### ISSUE TITLE
Incorrect D-Bus name used

### ISSUE THREAD

**Issue by hadess** [vincentbernat/dbus-mediakeys#2]
FYI, if you want to be compatible with gnome-settings-daemon in the future:
https://mail.gnome.org/archives/desktop-devel-list/2017-April/msg00069.html

**Comment by vincentbernat** [comment]
❦ 26 avril 2017 03:30 -0700, hadess <notifications@github.com> :

> FYI, if you want to be compatible with gnome-settings-daemon in the future:
> https://mail.gnome.org/archives/desktop-devel-list/2017-April/msg00069.html

Thanks! I have updated the source code.
-- 
Extreme fear can neither fight nor fly.
		-- William Shakespeare, "The Rape of Lucrece"
